USE `aio-life`;
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1001, 0, 'Analytics', '/analytics', 'dashboard/home/index', null, '{"icon": "lucide:home", "title": "主页", "backTop": false, "affixTab": true, "keepAlive": true, "maxIdleTime": 60}', null, -1, 1, null, null, 13, '2026-06-21 12:45:39', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1100, 0, 'Dashboard', '/dashboard', 'BasicLayout', null, '{"icon": "lucide:layout-dashboard", "title": "仪表盘"}', null, 0, 0, null, null, 13, '2026-06-21 12:45:48', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1101, 1100, 'Workspace', '/workspace', 'dashboard/workspace/index', null, '{"icon": "carbon:workspace", "title": "工作台"}', null, 0, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1200, 0, 'TaskCenter', '/task', 'BasicLayout', null, '{"icon": "mdi:clipboard-text-clock-outline", "title": "任务"}', null, 1, 1, null, null, 13, '2026-06-26 21:36:07', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1201, 1200, 'TaskCenterTodo', '/task/todo', 'task-center/todo/index', null, '{"icon": "mdi:format-list-checks", "title": "待办"}', null, 0, 1, null, null, 13, '2026-06-26 21:36:13', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1300, 0, 'TimeManagement', '/time', 'BasicLayout', null, '{"icon": "mdi:clock-outline", "title": "时间", "keepAlive": true}', null, 2, 1, null, null, 13, '2026-06-21 12:46:00', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1301, 1300, 'TimeTracker', '/time/time-tracker', 'time/time-tracker/index', null, '{"icon": "mdi:history", "title": "时迹", "backTop": false, "keepAlive": true, "maxIdleTime": 60}', null, 0, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1302, 1300, 'TimeTrackerDashboard', '/time/dashboard', 'time/dashboard/index', null, '{"icon": "mdi:view-dashboard-outline", "title": "看板", "backTop": false, "keepAlive": true}', null, 1, 0, null, null, 13, '2026-06-19 15:13:51', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1303, 1300, 'CategoryConfig', '/time/my-categories', 'time/time-tracker/category-config/index', null, '{"icon": "mdi:tag-multiple-outline", "title": "我的分类", "backTop": false}', null, 2, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1304, 1300, 'TimeTrackerCategoryAdmin', '/time/category-admin', 'time/time-tracker/admin/index', null, '{"icon": "mdi:shield-account-outline", "title": "分类管理（管理员）", "backTop": false}', 'admin', 3, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1400, 0, 'Coding', '/coding', 'BasicLayout', null, '{"icon": "lucide:code-2", "title": "编程", "keepAlive": true}', null, 7, 1, null, null, 13, '2026-06-21 12:44:52', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1401, 1400, 'GithubGraph', '/coding/github', 'coding/github/index', null, '{"icon": "mdi:github", "title": "Github", "backTop": false}', null, 1, 1, null, null, 13, '2026-06-21 12:43:44', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1402, 1400, 'LeetCode', '/coding/leetcode', 'coding/leetcode/index', null, '{"icon": "devicon:leetcode", "title": "LeetCode"}', null, 2, 1, null, null, 13, '2026-06-21 12:43:44', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1500, 0, 'Demos', '/record', 'BasicLayout', null, '{"icon": "ic:baseline-view-in-ar", "title": "记录", "keepAlive": true}', null, 3, 1, null, null, 13, '2026-06-21 12:46:06', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1501, 1500, 'exercise', '/record/exercise', 'my-hub/exercise/index', null, '{"icon": "mdi:run-fast", "title": "运动", "backTop": false}', null, 0, 1, null, null, 13, '2026-06-19 17:41:31', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1502, 1500, 'videoWatch', '/record/videoWatch', 'my-hub/videoWatch/index', null, '{"icon": "mdi:video-vintage", "title": "视频观看", "backTop": false}', null, 1, 1, null, null, 13, '2026-06-19 17:44:00', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1503, 1500, 'think', '/record/think', 'my-hub/think/index', null, '{"icon": "mdi:lightbulb-on-outline", "title": "闪念", "backTop": false}', null, 2, 1, null, null, 13, '2026-06-19 17:43:51', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1504, 1500, 'memo', '/record/memo', 'my-hub/memo/index', null, '{"icon": "mdi:note-text-outline", "title": "笔记", "backTop": false}', null, 3, 1, null, null, 13, '2026-06-19 17:43:41', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1505, 1500, 'performance', '/record/performance', 'my-hub/performance/index', null, '{"icon": "mdi:chart-line-variant", "title": "活动", "backTop": false}', null, 4, 1, null, null, 13, '2026-06-19 17:43:31', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1506, 1500, 'milestone', '/record/milestone', 'my-hub/milestone/index', null, '{"icon": "mdi:flag-variant", "title": "里程碑", "backTop": false}', null, 5, 1, null, null, 13, '2026-06-19 17:43:23', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1507, 1500, 'anniversary', '/record/anniversary', 'my-hub/anniversary/index', null, '{"icon": "mdi:calendar-heart", "title": "纪念日", "backTop": false}', null, 6, 1, null, null, 13, '2026-06-19 17:43:13', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1508, 1800, 'exerciseCategoryConfig', '/my-hub/exercise/category-config', 'my-hub/exercise/category-config/index', null, '{"icon": "mdi:format-list-bulleted-type", "title": "分类配置", "backTop": false}', null, 7, 1, null, null, 13, '2026-06-07 14:42:47', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1509, 1500, 'feedbackCenter', '/my-hub/feedback', 'my-hub/feedback/index', null, '{"icon": "mdi:message-alert-outline", "title": "反馈中心", "backTop": false}', null, 10, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1510, 1500, 'honor', '/my-hub/honor', 'my-hub/honor/index', null, '{"icon": "mdi:trophy-outline", "title": "荣誉中心", "backTop": false}', null, 7, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1600, 0, 'FinanceManagement', '/finance', 'BasicLayout', null, '{"icon": "mdi:finance", "title": "财务", "keepAlive": true}', null, 4, 1, null, null, 13, '2026-06-21 12:46:13', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1601, 1600, 'financeDashboard', '/finance/dashboard', 'my-hub/finance-dashboard/index', null, '{"icon": "mdi:chart-areaspline", "title": "概览", "backTop": false}', null, 0, 1, null, null, 13, '2026-06-20 12:50:41', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1602, 1600, 'incomeManagement', '/finance/income', 'my-hub/income/index', null, '{"icon": "mdi:cash-plus", "title": "收入", "backTop": false}', null, 1, 1, null, null, 13, '2026-06-20 12:50:48', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1603, 1600, 'expenseManagement', '/finance/expense', 'my-hub/expense/index', null, '{"icon": "mdi:cash-minus", "title": "支出", "backTop": false}', null, 2, 1, null, null, 13, '2026-06-20 12:50:54', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1604, 1600, 'alipayImport', '/finance/import', 'my-hub/expense/import', null, '{"icon": "mdi:import", "title": "账单导入", "backTop": false}', null, 3, 1, null, null, 13, '2026-06-20 12:51:00', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1700, 0, 'Goods', '/goods', 'BasicLayout', null, '{"icon": "lucide:package", "title": "物品", "keepAlive": true}', null, 5, 1, null, null, 13, '2026-06-21 12:46:24', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1701, 1700, 'device', '/my-hub/device', 'my-hub/device/index', null, '{"icon": "mdi:monitor-dashboard", "title": "设备墙", "backTop": false}', null, 0, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1702, 1700, 'Wardrobe', '/wardrobe', 'wardrobe/index', null, '{"icon": "ant-design:book-outlined", "title": "衣柜", "backTop": false}', null, 1, 1, null, null, 13, '2026-06-25 23:17:29', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1800, 0, 'ConfigManagement', '/config', 'BasicLayout', null, '{"icon": "mdi:cog-outline", "title": "配置管理", "keepAlive": true}', 'admin', 9, 1, null, null, 13, '2026-06-21 12:46:36', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1801, 1800, 'sysDictType', '/config-management/sysDictType', 'config-management/sysDictType/index', null, '{"icon": "mdi:book-settings-outline", "title": "字典类型", "backTop": false}', 'admin', 0, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1802, 1800, 'sysDictData', '/config-management/sysDictData', 'config-management/sysDictData/index', null, '{"icon": "mdi:database-search-outline", "title": "字典数据", "backTop": false}', 'admin', 1, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1900, 0, 'System', '/system', 'BasicLayout', null, '{"icon": "mdi:shield-account-outline", "title": "系统管理", "keepAlive": true}', 'admin', 10, 1, null, null, 13, '2026-06-21 12:46:41', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1901, 1900, 'UserCenter', '/system/user', 'system/user/index', null, '{"icon": "mdi:account-group-outline", "title": "用户中心"}', 'admin', 0, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1902, 1900, 'MenuManagement', '/system/menu', 'system/menu/index', null, '{"icon": "mdi:menu-open", "title": "菜单管理"}', 'admin', 1, 1, null, null, 13, '2026-06-13 13:01:09', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1903, 1900, 'UserDictAdmin', '/system/user-dict', 'system/user-dict/index', null, '{"icon": "mdi:book-open-page-variant", "title": "用户字典管理"}', 'admin', 3, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1904, 1900, 'FeedbackAdmin', '/system/feedback', 'system/feedback/index', null, '{"icon": "mdi:message-alert-outline", "title": "反馈管理"}', 'admin', 3, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1905, 1900, 'SystemConfig', '/system/config', 'system/config/index', null, '{"icon": "mdi:cog-outline", "title": "系统配置"}', 'admin', 4, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (2000, 0, 'Message', '/message', 'message/index', null, '{"icon": "ant-design:message-outlined", "title": "消息中心", "hideInMenu": false, "fullPathKey": false}', null, 10, 1, null, null, 13, '2026-06-21 12:46:46', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (2100, 0, 'VbenAbout', '/vben-admin/about', '_core/about/index', null, '{"icon": "lucide:copyright", "title": "关于"}', 'admin', 9999, 1, null, null, 13, '2026-06-21 12:47:03', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (2200, 0, 'Profile', '/profile', '_core/profile/index', null, '{"icon": "lucide:user", "title": "个人中心", "hideInMenu": true}', null, 9998, 1, null, null, null, null, 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (2300, 0, 'MCP', '/mcp', 'BasicLayout', null, '{"icon": "carbon:tools", "title": "研发管理", "keepAlive": true}', null, 20, 1, null, null, 13, '2026-06-21 12:46:57', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (2301, 2300, 'mcpTools', '/mcp/tools', 'mcp/tools/index', null, '{"icon": "carbon:cube", "title": "MCP 工具列表", "backTop": false}', null, 0, 1, null, null, 13, '2026-05-29 23:57:00', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (2302, 0, 'Relationship', '/relationship', 'BasicLayout', null, '{"icon": "ant-design:team-outlined", "order": 8, "title": "关系图谱", "keepAlive": true}', null, 8, 1, null, null, 13, '2026-06-20 21:58:28', 1);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (2303, 1500, 'RelationshipGraph', '/relationship/graph', 'relationship/index', null, '{"icon": "ant-design:team-outlined", "title": "关系图谱", "backTop": false}', null, 10, 1, null, null, 13, '2026-06-20 22:02:59', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (1508222, 1500, 'Movie', '/record/movie', 'my-hub/movie/index', null, '{"icon": "mdi:movie-open-play-outline", "title": "观影", "backTop": false}', null, 7, 1, null, null, 13, '2026-06-19 17:43:01', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (2049879990130667522, 0, 'PasswordManager', '/passwordP', 'password-manager/index', null, '{"icon": "mdi:clipboard-text-clock-outline", "order": 1, "title": "密码"}', null, 0, 1, 13, '2026-04-30 23:54:09', 13, '2026-05-20 22:17:27', 1);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (2049881372799758338, 1500, 'PasswordManagerIndex', '/record/password', 'password-manager/index', null, '{"icon": "ant-design:key-outlined", "title": "密码"}', null, 0, 1, 13, '2026-04-30 23:59:39', 13, '2026-06-19 17:44:11', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (2054205291710668802, 1200, 'TaskCenterGoal', '/task/goal', 'task-center/goal/index', null, '{"icon": "mdi:target", "title": "目标"}', null, 0, 1, 13, '2026-05-12 22:21:21', 13, '2026-06-26 21:36:20', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (2056010094796967937, 1400, 'CsdnDashboard', '/coding/csdn', 'coding/csdn/index', null, '{"icon": "simple-icons:csdn", "title": "CSDN", "backTop": false}', null, 3, 1, 13, '2026-05-17 21:53:00', 13, '2026-06-21 12:43:44', 0);
INSERT IGNORE INTO sys_menu (id, parent_id, name, path, component, redirect, meta, roles, sort, status, create_user, create_time, update_user, update_time, is_deleted) VALUES (2056010094796967938, 1500, 'readRecord', '/record/read', 'my-hub/read-record/index', null, '{"icon": "mdi:book-open-page-variant", "title": "阅读", "backTop": false}', null, 8, 1, null, null, 13, '2026-06-20 22:03:11', 0);

-- 会员菜单（提取自 1_init_table/2026-08-06_create_membership_record.sql，2026-08-18 合并重建时迁移）
INSERT IGNORE INTO `sys_menu` (`id`, `parent_id`, `name`, `path`, `component`, `redirect`, `meta`, `roles`, `sort`, `status`, `is_deleted`)
VALUES
(1703, 1700, 'Membership', '/membership', 'membership/index', NULL,
 JSON_OBJECT('icon','ant-design:gift-outlined','title','会员'),
 NULL, 2, 1, 0);
